imports:
    - { resource: "services/form.yml" }
    - { resource: "services/gateway_factory.yml" }
    - { resource: "services/action.yml" }

services:
    bitbag.mercanet_bnp_paribas.bridge.mercanet_bnp_paribas_bridge:
        class: BitBag\MercanetBnpParibasPlugin\Bridge\MercanetBnpParibasBridge
        public: true
        arguments:
            - '@request_stack'
